const data = {
  status: "success",
  items: [
    {
      id: 1,
      tittle: "Pizza Americana",
      price: 9900,
      description: "Jamón, carne, salchicha y pepperoni",
      category: "pizza",
      image: "https://i.imgur.com/Q0DZ4ai.jpeg",
      cantidad: 1,
    },
    {
      id: 2,
      tittle: "Pizza BBQ Chicken",
      price: 9900,
      description: "Salsa Barbecue, pollo y cebolla",
      category: "pizza",
      image: "https://i.imgur.com/aQxWLaz.jpeg",
      cantidad: 1,
    },
    {
      id: 3,
      tittle: "Pizza Campesina",
      price: 9900,
      description: "Pollo, pimiento y champiñón",
      category: "pizza",
      image: "https://i.imgur.com/3dsHcer.jpeg",
      cantidad: 1,
    },
    {
      id: 4,
      tittle: "Pizza Hawaiana",
      price: 9900,
      description: "Pollo, jamón y piña",
      category: "pizza",
      image: "https://i.imgur.com/hU3N7E7.jpeg",
      cantidad: 1,
    },
    {
      id: 5,
      tittle: "Pizza Mechada BBQ",
      price: 9900,
      description: "Carne mechada, tomate y cebolla",
      category: "pizza",
      image: "https://i.imgur.com/d4MCwTV.jpeg",
      cantidad: 1,
    },
    {
      id: 6,
      tittle: "Pizza Vegan Queen",
      price: 9900,
      description: "Chmapiñón, pimiento, cebolla, choclo y tomate",
      category: "pizza",
      image: "https://i.imgur.com/140Lode.jpeg",
      cantidad: 1,
    },
    {
      id: 7,
      tittle: "Bebida Coca-Cola 1.5L",
      price: 1300,
      category: "bebestible",
      image: "https://i.imgur.com/OyIq8Wo.jpeg",
      cantidad: 1,
    },
    {
      id: 8,
      tittle: "Bebida Fanta 1.5L",
      price: 1200,
      category: "bebestible",
      image: "https://i.imgur.com/Vr2VC89.jpeg",
      cantidad: 1,
    },
    {
      id: 9,
      tittle: "Cachantun con gas 1.5L",
      price: 1000,
      category: "bebestible",
      image: "https://i.imgur.com/329fXkn.jpeg",
      cantidad: 1,
    },
    {
      id: 10,
      tittle: "Cachantun sin gas 1.5L",
      price: 900,
      category: "bebestible",
      image: "https://i.imgur.com/FGwmQxt.jpeg",
      cantidad: 1,
    },
    {
      id: 11,
      tittle: "Jugo Watts Durazno 1.5L",
      price: 1100,
      category: "bebestible",
      image: "https://i.imgur.com/Iec8J37.jpeg",
      cantidad: 1,
    },
    {
      id: 12,
      tittle: "Jugo Watts Piña 1.5L",
      price: 1100,
      category: "bebestible",
      image: "https://i.imgur.com/e1yi7bP.jpeg",
      cantidad: 1,
    },
    {
      id: 13,
      tittle: "Salsa BBQ",
      price: 1000,
      category: "salsa",
      image: "https://i.imgur.com/jNDN6Nr.jpeg",
      cantidad: 1,
    },
    {
      id: 14,
      tittle: "Salsa Garlic",
      price: 1000,
      category: "salsa",
      image: "https://i.imgur.com/eGzL4GS.jpeg",
      cantidad: 1,
    },
    {
      id: 15,
      tittle: "Salsa de Tomate",
      price: 1000,
      category: "salsa",
      image: "https://i.imgur.com/2xA0Vze.jpeg",
      cantidad: 1,
    },
    {
      id: 16,
      tittle: "Salsa Picante",
      price: 1000,
      category: "salsa",
      image: "https://i.imgur.com/bJGeA92.jpeg",
      cantidad: 1,
    },
    {
      id: 17,
      tittle: "Pizza personalizada",
      price: 14990,
      description: [],
      category: "pizza",
      image: "https://i.imgur.com/bJGeA92.jpeg",
      cantidad: 1,
    },    
  ],
  especiales: [],
};

export default data;
